---
language: python
sudo: false
cache: pip
matrix:
  allow_failures:
    - python: nightly
    - env: DJANGO="Django>=3.0b1,<3.1"
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
  exclude:
    - python: "2.7"
      env: DJANGO="Django>=2.1,<2.2"
    - python: "2.7"
      env: DJANGO="Django>=2.2,<2.3"
    - python: "2.7"
      env: DJANGO="Django>=3.0b1,<3.1"
    - python: "2.7"
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
    - python: "3.5"
      env: DJANGO="Django>=3.0b1,<3.1"
    - python: "3.5"
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
env:
  - DJANGO="Django>=1.11,<1.12"
  - DJANGO="Django>=2.1,<2.2"
  - DJANGO="Django>=2.2,<2.3"
  - DJANGO="Django>=3.0b1,<3.1"
  - DJANGO="https://github.com/django/django/archive/master.tar.gz"
before_install:
  - pip install --quiet codecov
install:
  - pip install --quiet --pre $DJANGO
  - python setup.py -q install
script:
  - coverage run setup.py -v test
after_success:
  - codecov
